// src/pages/HomePage.vue
<script setup>
import HomeSearch from '@/components/HomeSearch.vue'
import HomeTrends from '@/components/HomeTrends.vue';
import HomePopular from '@/components/HomePopular.vue';
import HomeTrailers from '@/components/HomeTrailers.vue';
</script>

<template>
	<main>
		<HomeSearch />
    <HomeTrends />
		<HomeTrailers />
		<HomePopular />
	</main>
</template>

// src/pages/HomePage.jsx
import React from 'react'

import HomeSearch from '../components/home/HomeSearch.jsx'
import HomeTrends from '../components/home/HomeTrends.jsx'
import HomeTrailers from '../components/home/HomeTrailers.jsx'
import HomePopular from '../components/home/HomePopular.jsx'

export default function HomePage() {
  return (
    <main>
      <HomeSearch />
      <HomeTrends />
      <HomeTrailers />
      <HomePopular />
    </main>
  )
}
