// src/pages/SearchPage.jsx
import React, { useEffect } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'

import { applyLocale } from '../lib/locale.js'
import { useMoviesStore } from '../stores/useMoviesStore.js'
import SearchForm from '../components/form/SearchForm.jsx'
import ItemCard from '../components/ItemCard.jsx'
import Paginator from '../components/Paginator.jsx'

export default function SearchPage() {
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()

  const fetchSearch = useMoviesStore((s) => s.fetchSearch)
  const searchMovies = useMoviesStore((s) => s.searchMovies)

  const queryFromUrl = searchParams.get('query') || ''
  const pageFromUrl = Number(searchParams.get('page') || '1')

  const handleSearch = (query) => {
    const q = (query ?? queryFromUrl).trim()
    if (!q) return
    navigate(applyLocale(`/search?query=${encodeURIComponent(q)}&page=1`))
  }

  const handleChangePage = (options) => {
    const nextPage = options.page + 1
    const q = queryFromUrl
    if (!q) return
    navigate(applyLocale(`/search?query=${encodeURIComponent(q)}&page=${nextPage}`))
  }

  useEffect(() => {
    if (!queryFromUrl) return
    fetchSearch({ query: queryFromUrl, page: pageFromUrl })
  }, [queryFromUrl, pageFromUrl])

  return (
    <main className="container">
      <section className="search">
        <SearchForm
          key={queryFromUrl || 'search'}
          initialQuery={queryFromUrl}
          onSubmit={handleSearch}
        />

        <div className="search__content">
          <div className="search__content-items">
            {searchMovies.data.map((movie) => (
              <Link key={movie.id} to={applyLocale(`/${movie.media_type}/${movie.id}`)}>
                <ItemCard movie={movie} type="movie" />
              </Link>
            ))}
          </div>

          <Paginator page={pageFromUrl} rows={20} totalRecords={searchMovies.totalResults} onPage={handleChangePage} />
        </div>
      </section>
    </main>
  )
}

// src/pages/SearchPage.vue
<script setup>
import { onMounted, reactive } from 'vue'
import { useRouter } from 'vue-router'

import { moviesStore } from '@/stores/moviesStore'
import SearchForm from '@/components/form/SearchForm.vue'
import ItemCard from '@/components/ItemCard.vue'

const store = moviesStore()
const router = useRouter()

const searchQuery = reactive({
	query: router.currentRoute.value.query.query,
	page: Number(router.currentRoute.value.query.page),
})

const handleSearch = () => {
	console.log('search')
	if (!searchQuery.query) return
	searchQuery.page = 1
	store.fetchSearch({
		query: searchQuery.query,
		page: searchQuery.page,
	})
	router.push({
		name: 'search',
		query: { query: searchQuery.query, page: searchQuery.page },
	})
}

const handleChangePage = (options) => {
	// console.log(options)
	searchQuery.page = options.page + 1
	store.fetchSearch({
		query: searchQuery.query,
		page: searchQuery.page,
	})
	router.push({
		name: 'search',
		query: { query: searchQuery.query, page: searchQuery.page },
	})
}

onMounted(() => {
	store.fetchSearch({
		query: searchQuery.query,
		page: searchQuery.page,
	})
})
</script>

<template>
	<main class="container">
		<section class="search">
			<SearchForm
				:searchQuery="searchQuery"
				@submit="handleSearch"
			/>
			<div class="search__content">
				<div class="search__content-items">
					<RouterLink
						:to="{
							name: 'media-details',
							params: { mediaType: movie.media_type, id: movie.id },
						}"
						v-for="movie in store.searchMovies.data"
						:key="movie.id"
					>
						<ItemCard
							:movie="movie"
							type="movie"
						/>
					</RouterLink>
				</div>
				<!-- Pagination -->
				<PrimePaginator
					:first="(searchQuery.page - 1) * 20"
					:rows="20"
					:totalRecords="store.searchMovies.totalResults"
					:template="{
						'370px': 'PrevPageLink CurrentPageReport NextPageLink',
						'650px': 'FirstPageLink PrevPageLink CurrentPageReport NextPageLink LastPageLink',
						default: 'FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink',
					}"
					@page="handleChangePage"
				/>
			</div>
		</section>
	</main>
</template>
